// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"encoding/binary"
	"fmt"
	"math"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/metadata"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// SummaryDataPointValueAtQuantile is a quantile value within a Summary data point.
type SummaryDataPointValueAtQuantile struct {
	lazy     proto.LazyMessage
	Quantile float64
	Value    float64
}

var (
	protoPoolSummaryDataPointValueAtQuantile = sync.Pool{
		New: func() any {
			return &SummaryDataPointValueAtQuantile{}
		},
	}
)

func NewSummaryDataPointValueAtQuantile() *SummaryDataPointValueAtQuantile {
	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		return &SummaryDataPointValueAtQuantile{}
	}
	return protoPoolSummaryDataPointValueAtQuantile.Get().(*SummaryDataPointValueAtQuantile)
}

func DeleteSummaryDataPointValueAtQuantile(orig *SummaryDataPointValueAtQuantile, nullable bool) {
	if orig == nil {
		return
	}

	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		orig.Reset()
		return
	}

	orig.Reset()
	if nullable {
		protoPoolSummaryDataPointValueAtQuantile.Put(orig)
	}
}

func CopySummaryDataPointValueAtQuantile(dest, src *SummaryDataPointValueAtQuantile) *SummaryDataPointValueAtQuantile {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewSummaryDataPointValueAtQuantile()
	}
	src.EnsureDecoded()
	dest.EnsureDecoded()
	dest.Quantile = src.Quantile
	dest.Value = src.Value
	dest.MarkModified()

	return dest
}

func CopySummaryDataPointValueAtQuantileSlice(dest, src []SummaryDataPointValueAtQuantile) []SummaryDataPointValueAtQuantile {
	var newDest []SummaryDataPointValueAtQuantile
	if cap(dest) < len(src) {
		newDest = make([]SummaryDataPointValueAtQuantile, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteSummaryDataPointValueAtQuantile(&dest[i], false)
		}
	}
	for i := range src {
		CopySummaryDataPointValueAtQuantile(&newDest[i], &src[i])
	}
	return newDest
}

func CopySummaryDataPointValueAtQuantilePtrSlice(dest, src []*SummaryDataPointValueAtQuantile) []*SummaryDataPointValueAtQuantile {
	var newDest []*SummaryDataPointValueAtQuantile
	if cap(dest) < len(src) {
		newDest = make([]*SummaryDataPointValueAtQuantile, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewSummaryDataPointValueAtQuantile()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteSummaryDataPointValueAtQuantile(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewSummaryDataPointValueAtQuantile()
		}
	}
	for i := range src {
		CopySummaryDataPointValueAtQuantile(newDest[i], src[i])
	}
	return newDest
}

func (orig *SummaryDataPointValueAtQuantile) Reset() {
	*orig = SummaryDataPointValueAtQuantile{}
}

// LazyMessage returns the per-message protobuf lazy state.
func (orig *SummaryDataPointValueAtQuantile) LazyMessage() *proto.LazyMessage {
	return &orig.lazy
}

// SetLazyParent records the parent lazy state used for modification bubbling.
func (orig *SummaryDataPointValueAtQuantile) SetLazyParent(parent *proto.LazyMessage) {
	orig.lazy.SetParent(parent)
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *SummaryDataPointValueAtQuantile) MarshalJSON(dest *json.Stream) {
	orig.EnsureDecoded()
	dest.WriteObjectStart()
	if orig.Quantile != float64(0) {
		dest.WriteObjectField("quantile")
		dest.WriteFloat64(orig.Quantile)
	}
	if orig.Value != float64(0) {
		dest.WriteObjectField("value")
		dest.WriteFloat64(orig.Value)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *SummaryDataPointValueAtQuantile) UnmarshalJSON(iter *json.Iterator) {
	orig.Reset()
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "quantile":
			orig.Quantile = iter.ReadFloat64()
		case "value":
			orig.Value = iter.ReadFloat64()
		default:
			iter.Skip()
		}
	}
}

func (orig *SummaryDataPointValueAtQuantile) SizeProto() int {
	if orig.lazy.HasBytes() {
		return len(orig.lazy.Bytes())
	}
	var n int
	var l int
	_ = l
	if orig.Quantile != float64(0) {
		n += 9
	}
	if orig.Value != float64(0) {
		n += 9
	}
	return n
}

func (orig *SummaryDataPointValueAtQuantile) MarshalProto(buf []byte) int {
	if orig.lazy.HasBytes() {
		return copy(buf[len(buf)-len(orig.lazy.Bytes()):], orig.lazy.Bytes())
	}
	pos := len(buf)
	var l int
	_ = l
	if orig.Quantile != float64(0) {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.Quantile))
		pos--
		buf[pos] = 0x9
	}
	if orig.Value != float64(0) {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.Value))
		pos--
		buf[pos] = 0x11
	}
	return len(buf) - pos
}

func (orig *SummaryDataPointValueAtQuantile) UnmarshalProto(buf []byte) error {
	if err := validateSummaryDataPointValueAtQuantileProto(buf); err != nil {
		return err
	}
	orig.Reset()
	orig.lazy.Init(buf, nil)
	return nil
}

// EnsureDecoded materializes this message's direct fields from the attached
// protobuf bytes. Embedded messages keep their own byte references and are
// decoded by their getters.
func (orig *SummaryDataPointValueAtQuantile) EnsureDecoded() {
	if orig == nil || !orig.lazy.NeedsDecode() {
		return
	}
	orig.ensureDecoded()
}

func (orig *SummaryDataPointValueAtQuantile) ensureDecoded() {
	if err := orig.decodeProto(orig.lazy.Bytes()); err != nil {
		// UnmarshalProto validates the full message tree before storing bytes,
		// so a decode failure here means the message was mutated externally.
		panic(err)
	}
	orig.lazy.MarkDecoded()
}

// MarkModified records that this message must be re-encoded from fields. It
// assumes callers already decoded any fields they need before clearing wire
// bytes; keeping decode out of this method avoids a redundant hot-path check.
func (orig *SummaryDataPointValueAtQuantile) MarkModified() {
	orig.lazy.MarkModified()
}

// DecodeAll recursively materializes this message tree and clears lazy state.
// It is primarily useful for tests and operations that require ordinary struct
// equality instead of protobuf passthrough semantics.
func (orig *SummaryDataPointValueAtQuantile) DecodeAll() {
	orig.EnsureDecoded()

	orig.lazy.Clear()
}

func validateSummaryDataPointValueAtQuantileProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantile", wireType)
			}
			_, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			_, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (orig *SummaryDataPointValueAtQuantile) decodeProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantile", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.Quantile = math.Float64frombits(num)

		case 2:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.Value = math.Float64frombits(num)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestSummaryDataPointValueAtQuantile() *SummaryDataPointValueAtQuantile {
	orig := NewSummaryDataPointValueAtQuantile()
	orig.Quantile = float64(3.1415926)
	orig.Value = float64(3.1415926)
	return orig
}

func GenTestSummaryDataPointValueAtQuantilePtrSlice() []*SummaryDataPointValueAtQuantile {
	orig := make([]*SummaryDataPointValueAtQuantile, 5)
	orig[0] = NewSummaryDataPointValueAtQuantile()
	orig[1] = GenTestSummaryDataPointValueAtQuantile()
	orig[2] = NewSummaryDataPointValueAtQuantile()
	orig[3] = GenTestSummaryDataPointValueAtQuantile()
	orig[4] = NewSummaryDataPointValueAtQuantile()
	return orig
}

func GenTestSummaryDataPointValueAtQuantileSlice() []SummaryDataPointValueAtQuantile {
	orig := make([]SummaryDataPointValueAtQuantile, 5)
	orig[1] = *GenTestSummaryDataPointValueAtQuantile()
	orig[3] = *GenTestSummaryDataPointValueAtQuantile()
	return orig
}
