// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/metadata"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// ExportPartialSuccess represents the details of a partially successful export request.
type ExportProfilesPartialSuccess struct {
	lazy             proto.LazyMessage
	ErrorMessage     string
	RejectedProfiles int64
}

var (
	protoPoolExportProfilesPartialSuccess = sync.Pool{
		New: func() any {
			return &ExportProfilesPartialSuccess{}
		},
	}
)

func NewExportProfilesPartialSuccess() *ExportProfilesPartialSuccess {
	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		return &ExportProfilesPartialSuccess{}
	}
	return protoPoolExportProfilesPartialSuccess.Get().(*ExportProfilesPartialSuccess)
}

func DeleteExportProfilesPartialSuccess(orig *ExportProfilesPartialSuccess, nullable bool) {
	if orig == nil {
		return
	}

	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		orig.Reset()
		return
	}

	orig.Reset()
	if nullable {
		protoPoolExportProfilesPartialSuccess.Put(orig)
	}
}

func CopyExportProfilesPartialSuccess(dest, src *ExportProfilesPartialSuccess) *ExportProfilesPartialSuccess {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewExportProfilesPartialSuccess()
	}
	src.EnsureDecoded()
	dest.EnsureDecoded()
	dest.RejectedProfiles = src.RejectedProfiles
	dest.ErrorMessage = src.ErrorMessage
	dest.MarkModified()

	return dest
}

func CopyExportProfilesPartialSuccessSlice(dest, src []ExportProfilesPartialSuccess) []ExportProfilesPartialSuccess {
	var newDest []ExportProfilesPartialSuccess
	if cap(dest) < len(src) {
		newDest = make([]ExportProfilesPartialSuccess, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteExportProfilesPartialSuccess(&dest[i], false)
		}
	}
	for i := range src {
		CopyExportProfilesPartialSuccess(&newDest[i], &src[i])
	}
	return newDest
}

func CopyExportProfilesPartialSuccessPtrSlice(dest, src []*ExportProfilesPartialSuccess) []*ExportProfilesPartialSuccess {
	var newDest []*ExportProfilesPartialSuccess
	if cap(dest) < len(src) {
		newDest = make([]*ExportProfilesPartialSuccess, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewExportProfilesPartialSuccess()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteExportProfilesPartialSuccess(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewExportProfilesPartialSuccess()
		}
	}
	for i := range src {
		CopyExportProfilesPartialSuccess(newDest[i], src[i])
	}
	return newDest
}

func (orig *ExportProfilesPartialSuccess) Reset() {
	*orig = ExportProfilesPartialSuccess{}
}

// LazyMessage returns the per-message protobuf lazy state.
func (orig *ExportProfilesPartialSuccess) LazyMessage() *proto.LazyMessage {
	return &orig.lazy
}

// SetLazyParent records the parent lazy state used for modification bubbling.
func (orig *ExportProfilesPartialSuccess) SetLazyParent(parent *proto.LazyMessage) {
	orig.lazy.SetParent(parent)
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *ExportProfilesPartialSuccess) MarshalJSON(dest *json.Stream) {
	orig.EnsureDecoded()
	dest.WriteObjectStart()
	if orig.RejectedProfiles != int64(0) {
		dest.WriteObjectField("rejectedProfiles")
		dest.WriteInt64(orig.RejectedProfiles)
	}
	if orig.ErrorMessage != "" {
		dest.WriteObjectField("errorMessage")
		dest.WriteString(orig.ErrorMessage)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *ExportProfilesPartialSuccess) UnmarshalJSON(iter *json.Iterator) {
	orig.Reset()
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "rejectedProfiles", "rejected_profiles":
			orig.RejectedProfiles = iter.ReadInt64()
		case "errorMessage", "error_message":
			orig.ErrorMessage = iter.ReadString()
		default:
			iter.Skip()
		}
	}
}

func (orig *ExportProfilesPartialSuccess) SizeProto() int {
	if orig.lazy.HasBytes() {
		return len(orig.lazy.Bytes())
	}
	var n int
	var l int
	_ = l
	if orig.RejectedProfiles != int64(0) {
		n += 1 + proto.Sov(uint64(orig.RejectedProfiles))
	}

	l = len(orig.ErrorMessage)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	return n
}

func (orig *ExportProfilesPartialSuccess) MarshalProto(buf []byte) int {
	if orig.lazy.HasBytes() {
		return copy(buf[len(buf)-len(orig.lazy.Bytes()):], orig.lazy.Bytes())
	}
	pos := len(buf)
	var l int
	_ = l
	if orig.RejectedProfiles != int64(0) {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.RejectedProfiles))
		pos--
		buf[pos] = 0x8
	}
	l = len(orig.ErrorMessage)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.ErrorMessage)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x12
	}
	return len(buf) - pos
}

func (orig *ExportProfilesPartialSuccess) UnmarshalProto(buf []byte) error {
	if err := validateExportProfilesPartialSuccessProto(buf); err != nil {
		return err
	}
	orig.Reset()
	orig.lazy.Init(buf, nil)
	return nil
}

// EnsureDecoded materializes this message's direct fields from the attached
// protobuf bytes. Embedded messages keep their own byte references and are
// decoded by their getters.
func (orig *ExportProfilesPartialSuccess) EnsureDecoded() {
	if orig == nil || !orig.lazy.NeedsDecode() {
		return
	}
	orig.ensureDecoded()
}

func (orig *ExportProfilesPartialSuccess) ensureDecoded() {
	if err := orig.decodeProto(orig.lazy.Bytes()); err != nil {
		// UnmarshalProto validates the full message tree before storing bytes,
		// so a decode failure here means the message was mutated externally.
		panic(err)
	}
	orig.lazy.MarkDecoded()
}

// MarkModified records that this message must be re-encoded from fields. It
// assumes callers already decoded any fields they need before clearing wire
// bytes; keeping decode out of this method avoids a redundant hot-path check.
func (orig *ExportProfilesPartialSuccess) MarkModified() {
	orig.lazy.MarkModified()
}

// DecodeAll recursively materializes this message tree and clears lazy state.
// It is primarily useful for tests and operations that require ordinary struct
// equality instead of protobuf passthrough semantics.
func (orig *ExportProfilesPartialSuccess) DecodeAll() {
	orig.EnsureDecoded()

	orig.lazy.Clear()
}

func validateExportProfilesPartialSuccessProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedProfiles", wireType)
			}
			_, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMessage", wireType)
			}
			_, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (orig *ExportProfilesPartialSuccess) decodeProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedProfiles", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.RejectedProfiles = int64(num)

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMessage", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.ErrorMessage = string(buf[startPos:pos])
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestExportProfilesPartialSuccess() *ExportProfilesPartialSuccess {
	orig := NewExportProfilesPartialSuccess()
	orig.RejectedProfiles = int64(13)
	orig.ErrorMessage = "test_errormessage"
	return orig
}

func GenTestExportProfilesPartialSuccessPtrSlice() []*ExportProfilesPartialSuccess {
	orig := make([]*ExportProfilesPartialSuccess, 5)
	orig[0] = NewExportProfilesPartialSuccess()
	orig[1] = GenTestExportProfilesPartialSuccess()
	orig[2] = NewExportProfilesPartialSuccess()
	orig[3] = GenTestExportProfilesPartialSuccess()
	orig[4] = NewExportProfilesPartialSuccess()
	return orig
}

func GenTestExportProfilesPartialSuccessSlice() []ExportProfilesPartialSuccess {
	orig := make([]ExportProfilesPartialSuccess, 5)
	orig[1] = *GenTestExportProfilesPartialSuccess()
	orig[3] = *GenTestExportProfilesPartialSuccess()
	return orig
}
