// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

type StringSliceWrapper struct {
	orig   *[]string
	state  *State
	marker *LazyMessage
}

func GetStringSliceOrig(ms StringSliceWrapper) *[]string {
	return ms.orig
}

func GetStringSliceState(ms StringSliceWrapper) *State {
	return ms.state
}

func GetStringSliceLazyMessage(ms StringSliceWrapper) *LazyMessage {
	return ms.marker
}

func NewStringSliceWrapper(orig *[]string, state *State) StringSliceWrapper {
	return NewStringSliceWrapperWithLazyMessage(orig, state, nil)
}

func NewStringSliceWrapperWithLazyMessage(orig *[]string, state *State, marker *LazyMessage) StringSliceWrapper {
	return StringSliceWrapper{orig: orig, state: state, marker: marker}
}

func GenTestStringSliceWrapper() StringSliceWrapper {
	orig := []string{"a", "b", "c"}
	return NewStringSliceWrapper(&orig, NewState())
}

func GenTestStringSlice() []string {
	return []string{"a", "b", "c"}
}
