// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/metadata"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// Traces is the top-level struct that is propagated through the traces pipeline.
// Use NewTraces to create new instance, zero-initialized instance is not valid for use.
type ExportTraceServiceRequest struct {
	ResourceSpans []*ResourceSpans
	lazy          proto.LazyMessage
}

var (
	protoPoolExportTraceServiceRequest = sync.Pool{
		New: func() any {
			return &ExportTraceServiceRequest{}
		},
	}
)

func NewExportTraceServiceRequest() *ExportTraceServiceRequest {
	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		return &ExportTraceServiceRequest{}
	}
	return protoPoolExportTraceServiceRequest.Get().(*ExportTraceServiceRequest)
}

func DeleteExportTraceServiceRequest(orig *ExportTraceServiceRequest, nullable bool) {
	if orig == nil {
		return
	}

	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		orig.Reset()
		return
	}
	for i := range orig.ResourceSpans {
		DeleteResourceSpans(orig.ResourceSpans[i], true)
	}
	orig.Reset()
	if nullable {
		protoPoolExportTraceServiceRequest.Put(orig)
	}
}

func CopyExportTraceServiceRequest(dest, src *ExportTraceServiceRequest) *ExportTraceServiceRequest {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewExportTraceServiceRequest()
	}
	src.EnsureDecoded()
	dest.EnsureDecoded()
	dest.ResourceSpans = CopyResourceSpansPtrSlice(dest.ResourceSpans, src.ResourceSpans)

	dest.MarkModified()

	return dest
}

func CopyExportTraceServiceRequestSlice(dest, src []ExportTraceServiceRequest) []ExportTraceServiceRequest {
	var newDest []ExportTraceServiceRequest
	if cap(dest) < len(src) {
		newDest = make([]ExportTraceServiceRequest, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteExportTraceServiceRequest(&dest[i], false)
		}
	}
	for i := range src {
		CopyExportTraceServiceRequest(&newDest[i], &src[i])
	}
	return newDest
}

func CopyExportTraceServiceRequestPtrSlice(dest, src []*ExportTraceServiceRequest) []*ExportTraceServiceRequest {
	var newDest []*ExportTraceServiceRequest
	if cap(dest) < len(src) {
		newDest = make([]*ExportTraceServiceRequest, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewExportTraceServiceRequest()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteExportTraceServiceRequest(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewExportTraceServiceRequest()
		}
	}
	for i := range src {
		CopyExportTraceServiceRequest(newDest[i], src[i])
	}
	return newDest
}

func (orig *ExportTraceServiceRequest) Reset() {
	*orig = ExportTraceServiceRequest{}
}

// LazyMessage returns the per-message protobuf lazy state.
func (orig *ExportTraceServiceRequest) LazyMessage() *proto.LazyMessage {
	return &orig.lazy
}

// SetLazyParent records the parent lazy state used for modification bubbling.
func (orig *ExportTraceServiceRequest) SetLazyParent(parent *proto.LazyMessage) {
	orig.lazy.SetParent(parent)
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *ExportTraceServiceRequest) MarshalJSON(dest *json.Stream) {
	orig.EnsureDecoded()
	dest.WriteObjectStart()
	if len(orig.ResourceSpans) > 0 {
		dest.WriteObjectField("resourceSpans")
		dest.WriteArrayStart()
		orig.ResourceSpans[0].MarshalJSON(dest)
		for i := 1; i < len(orig.ResourceSpans); i++ {
			dest.WriteMore()
			orig.ResourceSpans[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *ExportTraceServiceRequest) UnmarshalJSON(iter *json.Iterator) {
	orig.Reset()
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "resourceSpans", "resource_spans":
			for iter.ReadArray() {
				orig.ResourceSpans = append(orig.ResourceSpans, NewResourceSpans())
				orig.ResourceSpans[len(orig.ResourceSpans)-1].UnmarshalJSON(iter)
			}

		default:
			iter.Skip()
		}
	}
}

func (orig *ExportTraceServiceRequest) SizeProto() int {
	if orig.lazy.HasBytes() {
		return len(orig.lazy.Bytes())
	}
	var n int
	var l int
	_ = l
	for i := range orig.ResourceSpans {
		l = orig.ResourceSpans[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	return n
}

func (orig *ExportTraceServiceRequest) MarshalProto(buf []byte) int {
	if orig.lazy.HasBytes() {
		return copy(buf[len(buf)-len(orig.lazy.Bytes()):], orig.lazy.Bytes())
	}
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.ResourceSpans) - 1; i >= 0; i-- {
		l = orig.ResourceSpans[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	return len(buf) - pos
}

func (orig *ExportTraceServiceRequest) UnmarshalProto(buf []byte) error {
	if err := validateExportTraceServiceRequestProto(buf); err != nil {
		return err
	}
	orig.Reset()
	orig.lazy.Init(buf, nil)
	return nil
}

// EnsureDecoded materializes this message's direct fields from the attached
// protobuf bytes. Embedded messages keep their own byte references and are
// decoded by their getters.
func (orig *ExportTraceServiceRequest) EnsureDecoded() {
	if orig == nil || orig.lazy.IsDecoded() {
		return
	}
	if err := orig.decodeProto(orig.lazy.Bytes()); err != nil {
		// UnmarshalProto validates the full message tree before storing bytes,
		// so a decode failure here means the message was mutated externally.
		panic(err)
	}
	orig.lazy.MarkDecoded()
}

// MarkModified records that this message must be re-encoded from fields.
func (orig *ExportTraceServiceRequest) MarkModified() {
	orig.EnsureDecoded()
	orig.lazy.MarkModified()
}

// DecodeAll recursively materializes this message tree and clears lazy state.
// It is primarily useful for tests and operations that require ordinary struct
// equality instead of protobuf passthrough semantics.
func (orig *ExportTraceServiceRequest) DecodeAll() {
	orig.EnsureDecoded()
	for i := range orig.ResourceSpans {
		if orig.ResourceSpans[i] != nil {
			orig.ResourceSpans[i].DecodeAll()
		}
	}
	orig.lazy.Clear()
}

func validateExportTraceServiceRequestProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceSpans", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateResourceSpansProto(buf[startPos:pos])
			if err != nil {
				return err
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (orig *ExportTraceServiceRequest) decodeProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceSpans", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.ResourceSpans = append(orig.ResourceSpans, NewResourceSpans())
			orig.ResourceSpans[len(orig.ResourceSpans)-1].lazy.Init(buf[startPos:pos], &orig.lazy)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestExportTraceServiceRequest() *ExportTraceServiceRequest {
	orig := NewExportTraceServiceRequest()
	orig.ResourceSpans = []*ResourceSpans{{}, GenTestResourceSpans()}
	return orig
}

func GenTestExportTraceServiceRequestPtrSlice() []*ExportTraceServiceRequest {
	orig := make([]*ExportTraceServiceRequest, 5)
	orig[0] = NewExportTraceServiceRequest()
	orig[1] = GenTestExportTraceServiceRequest()
	orig[2] = NewExportTraceServiceRequest()
	orig[3] = GenTestExportTraceServiceRequest()
	orig[4] = NewExportTraceServiceRequest()
	return orig
}

func GenTestExportTraceServiceRequestSlice() []ExportTraceServiceRequest {
	orig := make([]ExportTraceServiceRequest, 5)
	orig[1] = *GenTestExportTraceServiceRequest()
	orig[3] = *GenTestExportTraceServiceRequest()
	return orig
}
