// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/metadata"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

func (m *Metric) GetData() any {
	if m != nil {
		m.EnsureDecoded()
		return m.Data
	}
	return nil
}

type Metric_Gauge struct {
	Gauge *Gauge
}

func (m *Metric) GetGauge() *Gauge {
	if v, ok := m.GetData().(*Metric_Gauge); ok {
		return v.Gauge
	}
	return nil
}

type Metric_Sum struct {
	Sum *Sum
}

func (m *Metric) GetSum() *Sum {
	if v, ok := m.GetData().(*Metric_Sum); ok {
		return v.Sum
	}
	return nil
}

type Metric_Histogram struct {
	Histogram *Histogram
}

func (m *Metric) GetHistogram() *Histogram {
	if v, ok := m.GetData().(*Metric_Histogram); ok {
		return v.Histogram
	}
	return nil
}

type Metric_ExponentialHistogram struct {
	ExponentialHistogram *ExponentialHistogram
}

func (m *Metric) GetExponentialHistogram() *ExponentialHistogram {
	if v, ok := m.GetData().(*Metric_ExponentialHistogram); ok {
		return v.ExponentialHistogram
	}
	return nil
}

type Metric_Summary struct {
	Summary *Summary
}

func (m *Metric) GetSummary() *Summary {
	if v, ok := m.GetData().(*Metric_Summary); ok {
		return v.Summary
	}
	return nil
}

// Metric represents one metric as a collection of datapoints.
// See Metric definition in OTLP: https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto
type Metric struct {
	Data        any
	lazy        proto.LazyMessage
	Name        string
	Description string
	Unit        string
	Metadata    []KeyValue
}

var (
	protoPoolMetric = sync.Pool{
		New: func() any {
			return &Metric{}
		},
	}

	ProtoPoolMetric_Gauge = sync.Pool{
		New: func() any {
			return &Metric_Gauge{}
		},
	}

	ProtoPoolMetric_Sum = sync.Pool{
		New: func() any {
			return &Metric_Sum{}
		},
	}

	ProtoPoolMetric_Histogram = sync.Pool{
		New: func() any {
			return &Metric_Histogram{}
		},
	}

	ProtoPoolMetric_ExponentialHistogram = sync.Pool{
		New: func() any {
			return &Metric_ExponentialHistogram{}
		},
	}

	ProtoPoolMetric_Summary = sync.Pool{
		New: func() any {
			return &Metric_Summary{}
		},
	}
)

func NewMetric() *Metric {
	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		return &Metric{}
	}
	return protoPoolMetric.Get().(*Metric)
}

func DeleteMetric(orig *Metric, nullable bool) {
	if orig == nil {
		return
	}

	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		orig.Reset()
		return
	}

	switch ov := orig.Data.(type) {
	case *Metric_Gauge:
		DeleteGauge(ov.Gauge, true)
		ov.Gauge = nil
		ProtoPoolMetric_Gauge.Put(ov)
	case *Metric_Sum:
		DeleteSum(ov.Sum, true)
		ov.Sum = nil
		ProtoPoolMetric_Sum.Put(ov)
	case *Metric_Histogram:
		DeleteHistogram(ov.Histogram, true)
		ov.Histogram = nil
		ProtoPoolMetric_Histogram.Put(ov)
	case *Metric_ExponentialHistogram:
		DeleteExponentialHistogram(ov.ExponentialHistogram, true)
		ov.ExponentialHistogram = nil
		ProtoPoolMetric_ExponentialHistogram.Put(ov)
	case *Metric_Summary:
		DeleteSummary(ov.Summary, true)
		ov.Summary = nil
		ProtoPoolMetric_Summary.Put(ov)
	}
	for i := range orig.Metadata {
		DeleteKeyValue(&orig.Metadata[i], false)
	}
	orig.Reset()
	if nullable {
		protoPoolMetric.Put(orig)
	}
}

func CopyMetric(dest, src *Metric) *Metric {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewMetric()
	}
	src.EnsureDecoded()
	dest.EnsureDecoded()
	dest.Name = src.Name
	dest.Description = src.Description
	dest.Unit = src.Unit
	switch t := src.Data.(type) {
	case *Metric_Gauge:
		var ov *Metric_Gauge
		if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
			ov = &Metric_Gauge{}
		} else {
			ov = ProtoPoolMetric_Gauge.Get().(*Metric_Gauge)
		}
		ov.Gauge = NewGauge()
		CopyGauge(ov.Gauge, t.Gauge)
		dest.Data = ov

	case *Metric_Sum:
		var ov *Metric_Sum
		if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
			ov = &Metric_Sum{}
		} else {
			ov = ProtoPoolMetric_Sum.Get().(*Metric_Sum)
		}
		ov.Sum = NewSum()
		CopySum(ov.Sum, t.Sum)
		dest.Data = ov

	case *Metric_Histogram:
		var ov *Metric_Histogram
		if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
			ov = &Metric_Histogram{}
		} else {
			ov = ProtoPoolMetric_Histogram.Get().(*Metric_Histogram)
		}
		ov.Histogram = NewHistogram()
		CopyHistogram(ov.Histogram, t.Histogram)
		dest.Data = ov

	case *Metric_ExponentialHistogram:
		var ov *Metric_ExponentialHistogram
		if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
			ov = &Metric_ExponentialHistogram{}
		} else {
			ov = ProtoPoolMetric_ExponentialHistogram.Get().(*Metric_ExponentialHistogram)
		}
		ov.ExponentialHistogram = NewExponentialHistogram()
		CopyExponentialHistogram(ov.ExponentialHistogram, t.ExponentialHistogram)
		dest.Data = ov

	case *Metric_Summary:
		var ov *Metric_Summary
		if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
			ov = &Metric_Summary{}
		} else {
			ov = ProtoPoolMetric_Summary.Get().(*Metric_Summary)
		}
		ov.Summary = NewSummary()
		CopySummary(ov.Summary, t.Summary)
		dest.Data = ov

	default:
		dest.Data = nil
	}
	dest.Metadata = CopyKeyValueSlice(dest.Metadata, src.Metadata)

	dest.MarkModified()

	return dest
}

func CopyMetricSlice(dest, src []Metric) []Metric {
	var newDest []Metric
	if cap(dest) < len(src) {
		newDest = make([]Metric, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteMetric(&dest[i], false)
		}
	}
	for i := range src {
		CopyMetric(&newDest[i], &src[i])
	}
	return newDest
}

func CopyMetricPtrSlice(dest, src []*Metric) []*Metric {
	var newDest []*Metric
	if cap(dest) < len(src) {
		newDest = make([]*Metric, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewMetric()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteMetric(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewMetric()
		}
	}
	for i := range src {
		CopyMetric(newDest[i], src[i])
	}
	return newDest
}

func (orig *Metric) Reset() {
	*orig = Metric{}
}

// LazyMessage returns the per-message protobuf lazy state.
func (orig *Metric) LazyMessage() *proto.LazyMessage {
	return &orig.lazy
}

// SetLazyParent records the parent lazy state used for modification bubbling.
func (orig *Metric) SetLazyParent(parent *proto.LazyMessage) {
	orig.lazy.SetParent(parent)
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *Metric) MarshalJSON(dest *json.Stream) {
	orig.EnsureDecoded()
	dest.WriteObjectStart()
	if orig.Name != "" {
		dest.WriteObjectField("name")
		dest.WriteString(orig.Name)
	}
	if orig.Description != "" {
		dest.WriteObjectField("description")
		dest.WriteString(orig.Description)
	}
	if orig.Unit != "" {
		dest.WriteObjectField("unit")
		dest.WriteString(orig.Unit)
	}
	switch orig := orig.Data.(type) {
	case *Metric_Gauge:
		if orig.Gauge != nil {
			dest.WriteObjectField("gauge")
			orig.Gauge.MarshalJSON(dest)
		}
	case *Metric_Sum:
		if orig.Sum != nil {
			dest.WriteObjectField("sum")
			orig.Sum.MarshalJSON(dest)
		}
	case *Metric_Histogram:
		if orig.Histogram != nil {
			dest.WriteObjectField("histogram")
			orig.Histogram.MarshalJSON(dest)
		}
	case *Metric_ExponentialHistogram:
		if orig.ExponentialHistogram != nil {
			dest.WriteObjectField("exponentialHistogram")
			orig.ExponentialHistogram.MarshalJSON(dest)
		}
	case *Metric_Summary:
		if orig.Summary != nil {
			dest.WriteObjectField("summary")
			orig.Summary.MarshalJSON(dest)
		}
	}
	if len(orig.Metadata) > 0 {
		dest.WriteObjectField("metadata")
		dest.WriteArrayStart()
		orig.Metadata[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Metadata); i++ {
			dest.WriteMore()
			orig.Metadata[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *Metric) UnmarshalJSON(iter *json.Iterator) {
	orig.Reset()
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "name":
			orig.Name = iter.ReadString()
		case "description":
			orig.Description = iter.ReadString()
		case "unit":
			orig.Unit = iter.ReadString()

		case "gauge":
			{
				var ov *Metric_Gauge
				if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
					ov = &Metric_Gauge{}
				} else {
					ov = ProtoPoolMetric_Gauge.Get().(*Metric_Gauge)
				}
				ov.Gauge = NewGauge()
				ov.Gauge.UnmarshalJSON(iter)
				orig.Data = ov
			}
		case "sum":
			{
				var ov *Metric_Sum
				if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
					ov = &Metric_Sum{}
				} else {
					ov = ProtoPoolMetric_Sum.Get().(*Metric_Sum)
				}
				ov.Sum = NewSum()
				ov.Sum.UnmarshalJSON(iter)
				orig.Data = ov
			}
		case "histogram":
			{
				var ov *Metric_Histogram
				if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
					ov = &Metric_Histogram{}
				} else {
					ov = ProtoPoolMetric_Histogram.Get().(*Metric_Histogram)
				}
				ov.Histogram = NewHistogram()
				ov.Histogram.UnmarshalJSON(iter)
				orig.Data = ov
			}
		case "exponentialHistogram", "exponential_histogram":
			{
				var ov *Metric_ExponentialHistogram
				if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
					ov = &Metric_ExponentialHistogram{}
				} else {
					ov = ProtoPoolMetric_ExponentialHistogram.Get().(*Metric_ExponentialHistogram)
				}
				ov.ExponentialHistogram = NewExponentialHistogram()
				ov.ExponentialHistogram.UnmarshalJSON(iter)
				orig.Data = ov
			}
		case "summary":
			{
				var ov *Metric_Summary
				if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
					ov = &Metric_Summary{}
				} else {
					ov = ProtoPoolMetric_Summary.Get().(*Metric_Summary)
				}
				ov.Summary = NewSummary()
				ov.Summary.UnmarshalJSON(iter)
				orig.Data = ov
			}

		case "metadata":
			for iter.ReadArray() {
				orig.Metadata = append(orig.Metadata, KeyValue{})
				orig.Metadata[len(orig.Metadata)-1].UnmarshalJSON(iter)
			}

		default:
			iter.Skip()
		}
	}
}

func (orig *Metric) SizeProto() int {
	if orig.lazy.HasBytes() {
		return len(orig.lazy.Bytes())
	}
	var n int
	var l int
	_ = l

	l = len(orig.Name)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}

	l = len(orig.Description)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}

	l = len(orig.Unit)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	switch orig := orig.Data.(type) {
	case nil:
		_ = orig
		break
	case *Metric_Gauge:
		if orig.Gauge != nil {
			l = orig.Gauge.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	case *Metric_Sum:
		if orig.Sum != nil {
			l = orig.Sum.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	case *Metric_Histogram:
		if orig.Histogram != nil {
			l = orig.Histogram.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	case *Metric_ExponentialHistogram:
		if orig.ExponentialHistogram != nil {
			l = orig.ExponentialHistogram.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	case *Metric_Summary:
		if orig.Summary != nil {
			l = orig.Summary.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	}
	for i := range orig.Metadata {
		l = orig.Metadata[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	return n
}

func (orig *Metric) MarshalProto(buf []byte) int {
	if orig.lazy.HasBytes() {
		return copy(buf[len(buf)-len(orig.lazy.Bytes()):], orig.lazy.Bytes())
	}
	pos := len(buf)
	var l int
	_ = l
	l = len(orig.Name)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Name)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	l = len(orig.Description)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Description)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x12
	}
	l = len(orig.Unit)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Unit)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x1a
	}
	switch orig := orig.Data.(type) {
	case *Metric_Gauge:
		if orig.Gauge != nil {
			l = orig.Gauge.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x2a
		}
	case *Metric_Sum:
		if orig.Sum != nil {
			l = orig.Sum.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x3a
		}
	case *Metric_Histogram:
		if orig.Histogram != nil {
			l = orig.Histogram.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x4a
		}
	case *Metric_ExponentialHistogram:
		if orig.ExponentialHistogram != nil {
			l = orig.ExponentialHistogram.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x52
		}
	case *Metric_Summary:
		if orig.Summary != nil {
			l = orig.Summary.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x5a
		}
	}
	for i := len(orig.Metadata) - 1; i >= 0; i-- {
		l = orig.Metadata[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x62
	}
	return len(buf) - pos
}

func (orig *Metric) UnmarshalProto(buf []byte) error {
	if err := validateMetricProto(buf); err != nil {
		return err
	}
	orig.Reset()
	orig.lazy.Init(buf, nil)
	return nil
}

// EnsureDecoded materializes this message's direct fields from the attached
// protobuf bytes. Embedded messages keep their own byte references and are
// decoded by their getters.
func (orig *Metric) EnsureDecoded() {
	if orig == nil || !orig.lazy.NeedsDecode() {
		return
	}
	orig.ensureDecoded()
}

func (orig *Metric) ensureDecoded() {
	if err := orig.decodeProto(orig.lazy.Bytes()); err != nil {
		// UnmarshalProto validates the full message tree before storing bytes,
		// so a decode failure here means the message was mutated externally.
		panic(err)
	}
	orig.lazy.MarkDecoded()
}

// MarkModified records that this message must be re-encoded from fields. It
// assumes callers already decoded any fields they need before clearing wire
// bytes; keeping decode out of this method avoids a redundant hot-path check.
func (orig *Metric) MarkModified() {
	orig.lazy.MarkModified()
}

// DecodeAll recursively materializes this message tree and clears lazy state.
// It is primarily useful for tests and operations that require ordinary struct
// equality instead of protobuf passthrough semantics.
func (orig *Metric) DecodeAll() {
	orig.EnsureDecoded()

	if ov, ok := orig.Data.(*Metric_Gauge); ok && ov.Gauge != nil {
		ov.Gauge.DecodeAll()
	}

	if ov, ok := orig.Data.(*Metric_Sum); ok && ov.Sum != nil {
		ov.Sum.DecodeAll()
	}

	if ov, ok := orig.Data.(*Metric_Histogram); ok && ov.Histogram != nil {
		ov.Histogram.DecodeAll()
	}

	if ov, ok := orig.Data.(*Metric_ExponentialHistogram); ok && ov.ExponentialHistogram != nil {
		ov.ExponentialHistogram.DecodeAll()
	}

	if ov, ok := orig.Data.(*Metric_Summary); ok && ov.Summary != nil {
		ov.Summary.DecodeAll()
	}

	for i := range orig.Metadata {
		orig.Metadata[i].DecodeAll()
	}
	orig.lazy.Clear()
}

func validateMetricProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			_, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			_, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}

		case 3:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Unit", wireType)
			}
			_, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}

		case 5:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Gauge", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateGaugeProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 7:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateSumProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 9:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Histogram", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateHistogramProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 10:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ExponentialHistogram", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateExponentialHistogramProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 11:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateSummaryProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 12:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateKeyValueProto(buf[startPos:pos])
			if err != nil {
				return err
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (orig *Metric) decodeProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Name = string(buf[startPos:pos])

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Description = string(buf[startPos:pos])

		case 3:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Unit", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Unit = string(buf[startPos:pos])

		case 5:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Gauge", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			var ov *Metric_Gauge
			if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
				ov = &Metric_Gauge{}
			} else {
				ov = ProtoPoolMetric_Gauge.Get().(*Metric_Gauge)
			}
			ov.Gauge = NewGauge()
			ov.Gauge.lazy.Init(buf[startPos:pos], &orig.lazy)
			orig.Data = ov

		case 7:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			var ov *Metric_Sum
			if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
				ov = &Metric_Sum{}
			} else {
				ov = ProtoPoolMetric_Sum.Get().(*Metric_Sum)
			}
			ov.Sum = NewSum()
			ov.Sum.lazy.Init(buf[startPos:pos], &orig.lazy)
			orig.Data = ov

		case 9:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Histogram", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			var ov *Metric_Histogram
			if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
				ov = &Metric_Histogram{}
			} else {
				ov = ProtoPoolMetric_Histogram.Get().(*Metric_Histogram)
			}
			ov.Histogram = NewHistogram()
			ov.Histogram.lazy.Init(buf[startPos:pos], &orig.lazy)
			orig.Data = ov

		case 10:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ExponentialHistogram", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			var ov *Metric_ExponentialHistogram
			if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
				ov = &Metric_ExponentialHistogram{}
			} else {
				ov = ProtoPoolMetric_ExponentialHistogram.Get().(*Metric_ExponentialHistogram)
			}
			ov.ExponentialHistogram = NewExponentialHistogram()
			ov.ExponentialHistogram.lazy.Init(buf[startPos:pos], &orig.lazy)
			orig.Data = ov

		case 11:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			var ov *Metric_Summary
			if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
				ov = &Metric_Summary{}
			} else {
				ov = ProtoPoolMetric_Summary.Get().(*Metric_Summary)
			}
			ov.Summary = NewSummary()
			ov.Summary.lazy.Init(buf[startPos:pos], &orig.lazy)
			orig.Data = ov

		case 12:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Metadata = append(orig.Metadata, KeyValue{})
			(&orig.Metadata[len(orig.Metadata)-1]).lazy.Init(buf[startPos:pos], &orig.lazy)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestMetric() *Metric {
	orig := NewMetric()
	orig.Name = "test_name"
	orig.Description = "test_description"
	orig.Unit = "test_unit"
	orig.Data = &Metric_Gauge{Gauge: GenTestGauge()}
	orig.Metadata = []KeyValue{{}, *GenTestKeyValue()}
	return orig
}

func GenTestMetricPtrSlice() []*Metric {
	orig := make([]*Metric, 5)
	orig[0] = NewMetric()
	orig[1] = GenTestMetric()
	orig[2] = NewMetric()
	orig[3] = GenTestMetric()
	orig[4] = NewMetric()
	return orig
}

func GenTestMetricSlice() []Metric {
	orig := make([]Metric, 5)
	orig[1] = *GenTestMetric()
	orig[3] = *GenTestMetric()
	return orig
}
