// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/metadata"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// MetricsData represents the metrics data that can be stored in a persistent storage,
// OR can be embedded by other protocols that transfer OTLP metrics data but do not
// implement the OTLP protocol..
type MetricsData struct {
	ResourceMetrics []*ResourceMetrics
	lazy            proto.LazyMessage
}

var (
	protoPoolMetricsData = sync.Pool{
		New: func() any {
			return &MetricsData{}
		},
	}
)

func NewMetricsData() *MetricsData {
	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		return &MetricsData{}
	}
	return protoPoolMetricsData.Get().(*MetricsData)
}

func DeleteMetricsData(orig *MetricsData, nullable bool) {
	if orig == nil {
		return
	}

	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		orig.Reset()
		return
	}
	for i := range orig.ResourceMetrics {
		DeleteResourceMetrics(orig.ResourceMetrics[i], true)
	}
	orig.Reset()
	if nullable {
		protoPoolMetricsData.Put(orig)
	}
}

func CopyMetricsData(dest, src *MetricsData) *MetricsData {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewMetricsData()
	}
	src.EnsureDecoded()
	dest.EnsureDecoded()
	dest.ResourceMetrics = CopyResourceMetricsPtrSlice(dest.ResourceMetrics, src.ResourceMetrics)

	dest.MarkModified()

	return dest
}

func CopyMetricsDataSlice(dest, src []MetricsData) []MetricsData {
	var newDest []MetricsData
	if cap(dest) < len(src) {
		newDest = make([]MetricsData, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteMetricsData(&dest[i], false)
		}
	}
	for i := range src {
		CopyMetricsData(&newDest[i], &src[i])
	}
	return newDest
}

func CopyMetricsDataPtrSlice(dest, src []*MetricsData) []*MetricsData {
	var newDest []*MetricsData
	if cap(dest) < len(src) {
		newDest = make([]*MetricsData, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewMetricsData()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteMetricsData(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewMetricsData()
		}
	}
	for i := range src {
		CopyMetricsData(newDest[i], src[i])
	}
	return newDest
}

func (orig *MetricsData) Reset() {
	*orig = MetricsData{}
}

// LazyMessage returns the per-message protobuf lazy state.
func (orig *MetricsData) LazyMessage() *proto.LazyMessage {
	return &orig.lazy
}

// SetLazyParent records the parent lazy state used for modification bubbling.
func (orig *MetricsData) SetLazyParent(parent *proto.LazyMessage) {
	orig.lazy.SetParent(parent)
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *MetricsData) MarshalJSON(dest *json.Stream) {
	orig.EnsureDecoded()
	dest.WriteObjectStart()
	if len(orig.ResourceMetrics) > 0 {
		dest.WriteObjectField("resourceMetrics")
		dest.WriteArrayStart()
		orig.ResourceMetrics[0].MarshalJSON(dest)
		for i := 1; i < len(orig.ResourceMetrics); i++ {
			dest.WriteMore()
			orig.ResourceMetrics[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *MetricsData) UnmarshalJSON(iter *json.Iterator) {
	orig.Reset()
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "resourceMetrics", "resource_metrics":
			for iter.ReadArray() {
				orig.ResourceMetrics = append(orig.ResourceMetrics, NewResourceMetrics())
				orig.ResourceMetrics[len(orig.ResourceMetrics)-1].UnmarshalJSON(iter)
			}

		default:
			iter.Skip()
		}
	}
}

func (orig *MetricsData) SizeProto() int {
	if orig.lazy.HasBytes() {
		return len(orig.lazy.Bytes())
	}
	orig.EnsureDecoded()
	var n int
	var l int
	_ = l
	for i := range orig.ResourceMetrics {
		l = orig.ResourceMetrics[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	return n
}

func (orig *MetricsData) MarshalProto(buf []byte) int {
	if orig.lazy.HasBytes() {
		return copy(buf[len(buf)-len(orig.lazy.Bytes()):], orig.lazy.Bytes())
	}
	orig.EnsureDecoded()
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.ResourceMetrics) - 1; i >= 0; i-- {
		l = orig.ResourceMetrics[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	return len(buf) - pos
}

func (orig *MetricsData) UnmarshalProto(buf []byte) error {
	if err := validateMetricsDataProto(buf); err != nil {
		return err
	}
	orig.Reset()
	orig.lazy.Init(buf, nil)
	return nil
}

// EnsureDecoded materializes this message's direct fields from the attached
// protobuf bytes. Embedded messages keep their own byte references and are
// decoded by their getters.
func (orig *MetricsData) EnsureDecoded() {
	if orig == nil || orig.lazy.IsDecoded() {
		return
	}
	if err := orig.decodeProto(orig.lazy.Bytes()); err != nil {
		// UnmarshalProto validates the full message tree before storing bytes,
		// so a decode failure here means the message was mutated externally.
		panic(err)
	}
	orig.lazy.MarkDecoded()
}

// MarkModified records that this message must be re-encoded from fields.
func (orig *MetricsData) MarkModified() {
	orig.EnsureDecoded()
	orig.lazy.MarkModified()
}

// DecodeAll recursively materializes this message tree and clears lazy state.
// It is primarily useful for tests and operations that require ordinary struct
// equality instead of protobuf passthrough semantics.
func (orig *MetricsData) DecodeAll() {
	orig.EnsureDecoded()
	for i := range orig.ResourceMetrics {
		if orig.ResourceMetrics[i] != nil {
			orig.ResourceMetrics[i].DecodeAll()
		}
	}
	orig.lazy.Clear()
}

func validateMetricsDataProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceMetrics", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateResourceMetricsProto(buf[startPos:pos])
			if err != nil {
				return err
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (orig *MetricsData) decodeProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceMetrics", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.ResourceMetrics = append(orig.ResourceMetrics, NewResourceMetrics())
			orig.ResourceMetrics[len(orig.ResourceMetrics)-1].lazy.Init(buf[startPos:pos], &orig.lazy)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestMetricsData() *MetricsData {
	orig := NewMetricsData()
	orig.ResourceMetrics = []*ResourceMetrics{{}, GenTestResourceMetrics()}
	return orig
}

func GenTestMetricsDataPtrSlice() []*MetricsData {
	orig := make([]*MetricsData, 5)
	orig[0] = NewMetricsData()
	orig[1] = GenTestMetricsData()
	orig[2] = NewMetricsData()
	orig[3] = GenTestMetricsData()
	orig[4] = NewMetricsData()
	return orig
}

func GenTestMetricsDataSlice() []MetricsData {
	orig := make([]MetricsData, 5)
	orig[1] = *GenTestMetricsData()
	orig[3] = *GenTestMetricsData()
	return orig
}
