// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/metadata"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// ProfilesData represents the profiles data that can be stored in persistent storage,
// OR can be embedded by other protocols that transfer OTLP profiles data but do not
// implement the OTLP protocol.
type ProfilesData struct {
	ResourceProfiles []*ResourceProfiles
	Dictionary       ProfilesDictionary
	lazy             proto.LazyMessage
}

var (
	protoPoolProfilesData = sync.Pool{
		New: func() any {
			return &ProfilesData{}
		},
	}
)

func NewProfilesData() *ProfilesData {
	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		return &ProfilesData{}
	}
	return protoPoolProfilesData.Get().(*ProfilesData)
}

func DeleteProfilesData(orig *ProfilesData, nullable bool) {
	if orig == nil {
		return
	}

	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		orig.Reset()
		return
	}
	for i := range orig.ResourceProfiles {
		DeleteResourceProfiles(orig.ResourceProfiles[i], true)
	}
	DeleteProfilesDictionary(&orig.Dictionary, false)
	orig.Reset()
	if nullable {
		protoPoolProfilesData.Put(orig)
	}
}

func CopyProfilesData(dest, src *ProfilesData) *ProfilesData {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewProfilesData()
	}
	src.EnsureDecoded()
	dest.EnsureDecoded()
	dest.ResourceProfiles = CopyResourceProfilesPtrSlice(dest.ResourceProfiles, src.ResourceProfiles)

	CopyProfilesDictionary(&dest.Dictionary, &src.Dictionary)

	dest.MarkModified()

	return dest
}

func CopyProfilesDataSlice(dest, src []ProfilesData) []ProfilesData {
	var newDest []ProfilesData
	if cap(dest) < len(src) {
		newDest = make([]ProfilesData, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteProfilesData(&dest[i], false)
		}
	}
	for i := range src {
		CopyProfilesData(&newDest[i], &src[i])
	}
	return newDest
}

func CopyProfilesDataPtrSlice(dest, src []*ProfilesData) []*ProfilesData {
	var newDest []*ProfilesData
	if cap(dest) < len(src) {
		newDest = make([]*ProfilesData, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewProfilesData()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteProfilesData(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewProfilesData()
		}
	}
	for i := range src {
		CopyProfilesData(newDest[i], src[i])
	}
	return newDest
}

func (orig *ProfilesData) Reset() {
	*orig = ProfilesData{}
}

// LazyMessage returns the per-message protobuf lazy state.
func (orig *ProfilesData) LazyMessage() *proto.LazyMessage {
	return &orig.lazy
}

// SetLazyParent records the parent lazy state used for modification bubbling.
func (orig *ProfilesData) SetLazyParent(parent *proto.LazyMessage) {
	orig.lazy.SetParent(parent)
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *ProfilesData) MarshalJSON(dest *json.Stream) {
	orig.EnsureDecoded()
	dest.WriteObjectStart()
	if len(orig.ResourceProfiles) > 0 {
		dest.WriteObjectField("resourceProfiles")
		dest.WriteArrayStart()
		orig.ResourceProfiles[0].MarshalJSON(dest)
		for i := 1; i < len(orig.ResourceProfiles); i++ {
			dest.WriteMore()
			orig.ResourceProfiles[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	dest.WriteObjectField("dictionary")
	orig.Dictionary.MarshalJSON(dest)
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *ProfilesData) UnmarshalJSON(iter *json.Iterator) {
	orig.Reset()
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "resourceProfiles", "resource_profiles":
			for iter.ReadArray() {
				orig.ResourceProfiles = append(orig.ResourceProfiles, NewResourceProfiles())
				orig.ResourceProfiles[len(orig.ResourceProfiles)-1].UnmarshalJSON(iter)
			}

		case "dictionary":

			orig.Dictionary.UnmarshalJSON(iter)
		default:
			iter.Skip()
		}
	}
}

func (orig *ProfilesData) SizeProto() int {
	if orig.lazy.HasBytes() {
		return len(orig.lazy.Bytes())
	}
	var n int
	var l int
	_ = l
	for i := range orig.ResourceProfiles {
		l = orig.ResourceProfiles[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	l = orig.Dictionary.SizeProto()
	n += 1 + proto.Sov(uint64(l)) + l
	return n
}

func (orig *ProfilesData) MarshalProto(buf []byte) int {
	if orig.lazy.HasBytes() {
		return copy(buf[len(buf)-len(orig.lazy.Bytes()):], orig.lazy.Bytes())
	}
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.ResourceProfiles) - 1; i >= 0; i-- {
		l = orig.ResourceProfiles[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	l = orig.Dictionary.MarshalProto(buf[:pos])
	pos -= l
	pos = proto.EncodeVarint(buf, pos, uint64(l))
	pos--
	buf[pos] = 0x12

	return len(buf) - pos
}

func (orig *ProfilesData) UnmarshalProto(buf []byte) error {
	if err := validateProfilesDataProto(buf); err != nil {
		return err
	}
	orig.Reset()
	orig.lazy.Init(buf, nil)
	return nil
}

// EnsureDecoded materializes this message's direct fields from the attached
// protobuf bytes. Embedded messages keep their own byte references and are
// decoded by their getters.
func (orig *ProfilesData) EnsureDecoded() {
	if orig == nil || orig.lazy.IsDecoded() {
		return
	}
	if err := orig.decodeProto(orig.lazy.Bytes()); err != nil {
		// UnmarshalProto validates the full message tree before storing bytes,
		// so a decode failure here means the message was mutated externally.
		panic(err)
	}
	orig.lazy.MarkDecoded()
}

// MarkModified records that this message must be re-encoded from fields.
func (orig *ProfilesData) MarkModified() {
	orig.EnsureDecoded()
	orig.lazy.MarkModified()
}

// DecodeAll recursively materializes this message tree and clears lazy state.
// It is primarily useful for tests and operations that require ordinary struct
// equality instead of protobuf passthrough semantics.
func (orig *ProfilesData) DecodeAll() {
	orig.EnsureDecoded()
	for i := range orig.ResourceProfiles {
		if orig.ResourceProfiles[i] != nil {
			orig.ResourceProfiles[i].DecodeAll()
		}
	}
	orig.Dictionary.DecodeAll()
	orig.lazy.Clear()
}

func validateProfilesDataProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceProfiles", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateResourceProfilesProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Dictionary", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateProfilesDictionaryProto(buf[startPos:pos])
			if err != nil {
				return err
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (orig *ProfilesData) decodeProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceProfiles", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.ResourceProfiles = append(orig.ResourceProfiles, NewResourceProfiles())
			orig.ResourceProfiles[len(orig.ResourceProfiles)-1].lazy.Init(buf[startPos:pos], &orig.lazy)

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Dictionary", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length

			(&orig.Dictionary).lazy.Init(buf[startPos:pos], &orig.lazy)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestProfilesData() *ProfilesData {
	orig := NewProfilesData()
	orig.ResourceProfiles = []*ResourceProfiles{{}, GenTestResourceProfiles()}
	orig.Dictionary = *GenTestProfilesDictionary()
	return orig
}

func GenTestProfilesDataPtrSlice() []*ProfilesData {
	orig := make([]*ProfilesData, 5)
	orig[0] = NewProfilesData()
	orig[1] = GenTestProfilesData()
	orig[2] = NewProfilesData()
	orig[3] = GenTestProfilesData()
	orig[4] = NewProfilesData()
	return orig
}

func GenTestProfilesDataSlice() []ProfilesData {
	orig := make([]ProfilesData, 5)
	orig[1] = *GenTestProfilesData()
	orig[3] = *GenTestProfilesData()
	return orig
}
