// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/metadata"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// ResourceProfiles is a collection of profiles from a Resource.
type ResourceProfiles struct {
	Resource      Resource
	ScopeProfiles []*ScopeProfiles
	SchemaUrl     string
	lazy          proto.LazyMessage
}

var (
	protoPoolResourceProfiles = sync.Pool{
		New: func() any {
			return &ResourceProfiles{}
		},
	}
)

func NewResourceProfiles() *ResourceProfiles {
	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		return &ResourceProfiles{}
	}
	return protoPoolResourceProfiles.Get().(*ResourceProfiles)
}

func DeleteResourceProfiles(orig *ResourceProfiles, nullable bool) {
	if orig == nil {
		return
	}

	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		orig.Reset()
		return
	}
	DeleteResource(&orig.Resource, false)
	for i := range orig.ScopeProfiles {
		DeleteScopeProfiles(orig.ScopeProfiles[i], true)
	}

	orig.Reset()
	if nullable {
		protoPoolResourceProfiles.Put(orig)
	}
}

func CopyResourceProfiles(dest, src *ResourceProfiles) *ResourceProfiles {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewResourceProfiles()
	}
	src.EnsureDecoded()
	dest.EnsureDecoded()
	CopyResource(&dest.Resource, &src.Resource)

	dest.ScopeProfiles = CopyScopeProfilesPtrSlice(dest.ScopeProfiles, src.ScopeProfiles)

	dest.SchemaUrl = src.SchemaUrl
	dest.MarkModified()

	return dest
}

func CopyResourceProfilesSlice(dest, src []ResourceProfiles) []ResourceProfiles {
	var newDest []ResourceProfiles
	if cap(dest) < len(src) {
		newDest = make([]ResourceProfiles, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteResourceProfiles(&dest[i], false)
		}
	}
	for i := range src {
		CopyResourceProfiles(&newDest[i], &src[i])
	}
	return newDest
}

func CopyResourceProfilesPtrSlice(dest, src []*ResourceProfiles) []*ResourceProfiles {
	var newDest []*ResourceProfiles
	if cap(dest) < len(src) {
		newDest = make([]*ResourceProfiles, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewResourceProfiles()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteResourceProfiles(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewResourceProfiles()
		}
	}
	for i := range src {
		CopyResourceProfiles(newDest[i], src[i])
	}
	return newDest
}

func (orig *ResourceProfiles) Reset() {
	*orig = ResourceProfiles{}
}

// LazyMessage returns the per-message protobuf lazy state.
func (orig *ResourceProfiles) LazyMessage() *proto.LazyMessage {
	return &orig.lazy
}

// SetLazyParent records the parent lazy state used for modification bubbling.
func (orig *ResourceProfiles) SetLazyParent(parent *proto.LazyMessage) {
	orig.lazy.SetParent(parent)
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *ResourceProfiles) MarshalJSON(dest *json.Stream) {
	orig.EnsureDecoded()
	dest.WriteObjectStart()
	dest.WriteObjectField("resource")
	orig.Resource.MarshalJSON(dest)
	if len(orig.ScopeProfiles) > 0 {
		dest.WriteObjectField("scopeProfiles")
		dest.WriteArrayStart()
		orig.ScopeProfiles[0].MarshalJSON(dest)
		for i := 1; i < len(orig.ScopeProfiles); i++ {
			dest.WriteMore()
			orig.ScopeProfiles[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	if orig.SchemaUrl != "" {
		dest.WriteObjectField("schemaUrl")
		dest.WriteString(orig.SchemaUrl)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *ResourceProfiles) UnmarshalJSON(iter *json.Iterator) {
	orig.Reset()
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "resource":

			orig.Resource.UnmarshalJSON(iter)
		case "scopeProfiles", "scope_profiles":
			for iter.ReadArray() {
				orig.ScopeProfiles = append(orig.ScopeProfiles, NewScopeProfiles())
				orig.ScopeProfiles[len(orig.ScopeProfiles)-1].UnmarshalJSON(iter)
			}

		case "schemaUrl", "schema_url":
			orig.SchemaUrl = iter.ReadString()
		default:
			iter.Skip()
		}
	}
}

func (orig *ResourceProfiles) SizeProto() int {
	if orig.lazy.HasBytes() {
		return len(orig.lazy.Bytes())
	}
	var n int
	var l int
	_ = l
	l = orig.Resource.SizeProto()
	n += 1 + proto.Sov(uint64(l)) + l
	for i := range orig.ScopeProfiles {
		l = orig.ScopeProfiles[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}

	l = len(orig.SchemaUrl)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	return n
}

func (orig *ResourceProfiles) MarshalProto(buf []byte) int {
	if orig.lazy.HasBytes() {
		return copy(buf[len(buf)-len(orig.lazy.Bytes()):], orig.lazy.Bytes())
	}
	pos := len(buf)
	var l int
	_ = l
	l = orig.Resource.MarshalProto(buf[:pos])
	pos -= l
	pos = proto.EncodeVarint(buf, pos, uint64(l))
	pos--
	buf[pos] = 0xa

	for i := len(orig.ScopeProfiles) - 1; i >= 0; i-- {
		l = orig.ScopeProfiles[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x12
	}
	l = len(orig.SchemaUrl)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.SchemaUrl)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x1a
	}
	return len(buf) - pos
}

func (orig *ResourceProfiles) UnmarshalProto(buf []byte) error {
	if err := validateResourceProfilesProto(buf); err != nil {
		return err
	}
	orig.Reset()
	orig.lazy.Init(buf, nil)
	return nil
}

// EnsureDecoded materializes this message's direct fields from the attached
// protobuf bytes. Embedded messages keep their own byte references and are
// decoded by their getters.
func (orig *ResourceProfiles) EnsureDecoded() {
	if orig == nil || !orig.lazy.NeedsDecode() {
		return
	}
	orig.ensureDecoded()
}

func (orig *ResourceProfiles) ensureDecoded() {
	if err := orig.decodeProto(orig.lazy.Bytes()); err != nil {
		// UnmarshalProto validates the full message tree before storing bytes,
		// so a decode failure here means the message was mutated externally.
		panic(err)
	}
	orig.lazy.MarkDecoded()
}

// MarkModified records that this message must be re-encoded from fields. It
// assumes callers already decoded any fields they need before clearing wire
// bytes; keeping decode out of this method avoids a redundant hot-path check.
func (orig *ResourceProfiles) MarkModified() {
	orig.lazy.MarkModified()
}

// DecodeAll recursively materializes this message tree and clears lazy state.
// It is primarily useful for tests and operations that require ordinary struct
// equality instead of protobuf passthrough semantics.
func (orig *ResourceProfiles) DecodeAll() {
	orig.EnsureDecoded()
	orig.Resource.DecodeAll()
	for i := range orig.ScopeProfiles {
		if orig.ScopeProfiles[i] != nil {
			orig.ScopeProfiles[i].DecodeAll()
		}
	}

	orig.lazy.Clear()
}

func validateResourceProfilesProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Resource", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateResourceProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ScopeProfiles", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			err = validateScopeProfilesProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 3:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaUrl", wireType)
			}
			_, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (orig *ResourceProfiles) decodeProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Resource", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length

			(&orig.Resource).lazy.Init(buf[startPos:pos], &orig.lazy)

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ScopeProfiles", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.ScopeProfiles = append(orig.ScopeProfiles, NewScopeProfiles())
			orig.ScopeProfiles[len(orig.ScopeProfiles)-1].lazy.Init(buf[startPos:pos], &orig.lazy)

		case 3:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaUrl", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.SchemaUrl = string(buf[startPos:pos])
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestResourceProfiles() *ResourceProfiles {
	orig := NewResourceProfiles()
	orig.Resource = *GenTestResource()
	orig.ScopeProfiles = []*ScopeProfiles{{}, GenTestScopeProfiles()}
	orig.SchemaUrl = "test_schemaurl"
	return orig
}

func GenTestResourceProfilesPtrSlice() []*ResourceProfiles {
	orig := make([]*ResourceProfiles, 5)
	orig[0] = NewResourceProfiles()
	orig[1] = GenTestResourceProfiles()
	orig[2] = NewResourceProfiles()
	orig[3] = GenTestResourceProfiles()
	orig[4] = NewResourceProfiles()
	return orig
}

func GenTestResourceProfilesSlice() []ResourceProfiles {
	orig := make([]ResourceProfiles, 5)
	orig[1] = *GenTestResourceProfiles()
	orig[3] = *GenTestResourceProfiles()
	return orig
}
