// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: opentelemetry/proto/entities/v1/entities.proto

package v1

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"

	v1 "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	_ "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EntitiesData represents the entities data that can be stored in a persistent storage,
// OR can be embedded by other protocols that transfer OTLP entities data but do not
// implement the OTLP protocol.
//
// The main difference between this message and collector protocol is that
// in this message there will not be any "control" or "metadata" specific to
// OTLP protocol.
//
// When new fields are added into this message, the OTLP request MUST be updated
// as well.
type EntitiesData struct {
	ScopeEntities []*ScopeEntities `protobuf:"bytes,1,rep,name=scope_entities,json=scopeEntities,proto3" json:"scope_entities,omitempty"`
}

func (m *EntitiesData) Reset()         { *m = EntitiesData{} }
func (m *EntitiesData) String() string { return proto.CompactTextString(m) }
func (*EntitiesData) ProtoMessage()    {}
func (*EntitiesData) Descriptor() ([]byte, []int) {
	return fileDescriptor_23658fae9436c0cd, []int{0}
}
func (m *EntitiesData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EntitiesData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EntitiesData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EntitiesData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntitiesData.Merge(m, src)
}
func (m *EntitiesData) XXX_Size() int {
	return m.Size()
}
func (m *EntitiesData) XXX_DiscardUnknown() {
	xxx_messageInfo_EntitiesData.DiscardUnknown(m)
}

var xxx_messageInfo_EntitiesData proto.InternalMessageInfo

func (m *EntitiesData) GetScopeEntities() []*ScopeEntities {
	if m != nil {
		return m.ScopeEntities
	}
	return nil
}

// A collection of Entities produced by a Scope.
type ScopeEntities struct {
	// The instrumentation scope information for the entities in this message.
	// Semantically when InstrumentationScope isn't set, it is equivalent with
	// an empty instrumentation scope name (unknown).
	Scope        v1.InstrumentationScope `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope"`
	EntityEvents []*EntityEvent          `protobuf:"bytes,2,rep,name=entity_events,json=entityEvents,proto3" json:"entity_events,omitempty"`
	// This schema_url applies to all entities in the "entity_events" field.
	SchemaUrl string `protobuf:"bytes,3,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
}

func (m *ScopeEntities) Reset()         { *m = ScopeEntities{} }
func (m *ScopeEntities) String() string { return proto.CompactTextString(m) }
func (*ScopeEntities) ProtoMessage()    {}
func (*ScopeEntities) Descriptor() ([]byte, []int) {
	return fileDescriptor_23658fae9436c0cd, []int{1}
}
func (m *ScopeEntities) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScopeEntities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScopeEntities.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScopeEntities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopeEntities.Merge(m, src)
}
func (m *ScopeEntities) XXX_Size() int {
	return m.Size()
}
func (m *ScopeEntities) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopeEntities.DiscardUnknown(m)
}

var xxx_messageInfo_ScopeEntities proto.InternalMessageInfo

func (m *ScopeEntities) GetScope() v1.InstrumentationScope {
	if m != nil {
		return m.Scope
	}
	return v1.InstrumentationScope{}
}

func (m *ScopeEntities) GetEntityEvents() []*EntityEvent {
	if m != nil {
		return m.EntityEvents
	}
	return nil
}

func (m *ScopeEntities) GetSchemaUrl() string {
	if m != nil {
		return m.SchemaUrl
	}
	return ""
}

// The full state of the Entity.
type EntityEvent struct {
	// Time when this state was observed.
	TimeUnixNano uint64 `protobuf:"varint,1,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	// Type of the entity, e.g. "service", "host", etc.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Set of attributes that identify the entity.
	Id []v1.KeyValue `protobuf:"bytes,3,rep,name=id,proto3" json:"id"`
	// Types that are valid to be assigned to Data:
	//	*EntityEvent_State
	//	*EntityEvent_Delete
	Data isEntityEvent_Data `protobuf_oneof:"data"`
}

func (m *EntityEvent) Reset()         { *m = EntityEvent{} }
func (m *EntityEvent) String() string { return proto.CompactTextString(m) }
func (*EntityEvent) ProtoMessage()    {}
func (*EntityEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_23658fae9436c0cd, []int{2}
}
func (m *EntityEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EntityEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EntityEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EntityEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityEvent.Merge(m, src)
}
func (m *EntityEvent) XXX_Size() int {
	return m.Size()
}
func (m *EntityEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EntityEvent proto.InternalMessageInfo

type isEntityEvent_Data interface {
	isEntityEvent_Data()
	MarshalTo([]byte) (int, error)
	Size() int
}

type EntityEvent_State struct {
	State *EntityState `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`
}
type EntityEvent_Delete struct {
	Delete *EntityDelete `protobuf:"bytes,5,opt,name=delete,proto3,oneof" json:"delete,omitempty"`
}

func (*EntityEvent_State) isEntityEvent_Data()  {}
func (*EntityEvent_Delete) isEntityEvent_Data() {}

func (m *EntityEvent) GetData() isEntityEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EntityEvent) GetTimeUnixNano() uint64 {
	if m != nil {
		return m.TimeUnixNano
	}
	return 0
}

func (m *EntityEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EntityEvent) GetId() []v1.KeyValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *EntityEvent) GetState() *EntityState {
	if x, ok := m.GetData().(*EntityEvent_State); ok {
		return x.State
	}
	return nil
}

func (m *EntityEvent) GetDelete() *EntityDelete {
	if x, ok := m.GetData().(*EntityEvent_Delete); ok {
		return x.Delete
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EntityEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EntityEvent_State)(nil),
		(*EntityEvent_Delete)(nil),
	}
}

type EntityState struct {
	// Set of non-identifying attributes only.
	Attributes             []v1.KeyValue `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes"`
	DroppedAttributesCount uint32        `protobuf:"varint,5,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
}

func (m *EntityState) Reset()         { *m = EntityState{} }
func (m *EntityState) String() string { return proto.CompactTextString(m) }
func (*EntityState) ProtoMessage()    {}
func (*EntityState) Descriptor() ([]byte, []int) {
	return fileDescriptor_23658fae9436c0cd, []int{3}
}
func (m *EntityState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EntityState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EntityState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EntityState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityState.Merge(m, src)
}
func (m *EntityState) XXX_Size() int {
	return m.Size()
}
func (m *EntityState) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityState.DiscardUnknown(m)
}

var xxx_messageInfo_EntityState proto.InternalMessageInfo

func (m *EntityState) GetAttributes() []v1.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *EntityState) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

type EntityDelete struct {
}

func (m *EntityDelete) Reset()         { *m = EntityDelete{} }
func (m *EntityDelete) String() string { return proto.CompactTextString(m) }
func (*EntityDelete) ProtoMessage()    {}
func (*EntityDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_23658fae9436c0cd, []int{4}
}
func (m *EntityDelete) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EntityDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EntityDelete.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EntityDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityDelete.Merge(m, src)
}
func (m *EntityDelete) XXX_Size() int {
	return m.Size()
}
func (m *EntityDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityDelete.DiscardUnknown(m)
}

var xxx_messageInfo_EntityDelete proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EntitiesData)(nil), "opentelemetry.proto.entities.v1.EntitiesData")
	proto.RegisterType((*ScopeEntities)(nil), "opentelemetry.proto.entities.v1.ScopeEntities")
	proto.RegisterType((*EntityEvent)(nil), "opentelemetry.proto.entities.v1.EntityEvent")
	proto.RegisterType((*EntityState)(nil), "opentelemetry.proto.entities.v1.EntityState")
	proto.RegisterType((*EntityDelete)(nil), "opentelemetry.proto.entities.v1.EntityDelete")
}

func init() {
	proto.RegisterFile("opentelemetry/proto/entities/v1/entities.proto", fileDescriptor_23658fae9436c0cd)
}

var fileDescriptor_23658fae9436c0cd = []byte{
	// 554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x8d, 0x5d, 0x37, 0x52, 0x27, 0x8f, 0xc5, 0x08, 0x21, 0xab, 0x12, 0x4e, 0x64, 0x21, 0x11,
	0x21, 0xb0, 0x95, 0x76, 0xc3, 0x86, 0x05, 0x21, 0x85, 0x22, 0x04, 0x2d, 0x2e, 0xe9, 0x82, 0x8d,
	0x35, 0xb5, 0xaf, 0xc2, 0x48, 0xf6, 0x8c, 0x35, 0x1e, 0x47, 0xcd, 0x5f, 0xb0, 0x62, 0xc7, 0x0f,
	0xf0, 0x03, 0xfc, 0x42, 0x97, 0x15, 0x2b, 0x56, 0x08, 0x25, 0x3f, 0x82, 0x66, 0x6c, 0xa7, 0x29,
	0x8a, 0x94, 0x8a, 0xdd, 0x7d, 0x9c, 0x73, 0xee, 0xb9, 0x57, 0x63, 0x23, 0x8f, 0x67, 0xc0, 0x24,
	0x24, 0x90, 0x82, 0x14, 0x73, 0x3f, 0x13, 0x5c, 0x72, 0x1f, 0x98, 0xa4, 0x92, 0x42, 0xee, 0xcf,
	0x86, 0xab, 0xd8, 0xd3, 0x2d, 0xdc, 0xbb, 0x85, 0x2f, 0x8b, 0xde, 0x0a, 0x33, 0x1b, 0xee, 0xdf,
	0x9b, 0xf2, 0x29, 0x2f, 0x65, 0x54, 0x54, 0x22, 0xf6, 0x1f, 0x6f, 0x1a, 0x13, 0xf1, 0x34, 0xe5,
	0x4c, 0x0d, 0x29, 0xa3, 0x0a, 0xbb, 0xd1, 0x92, 0x80, 0x9c, 0x17, 0x22, 0x02, 0x85, 0xae, 0xe3,
	0x12, 0xef, 0x02, 0x6a, 0x1f, 0x55, 0x06, 0xc6, 0x44, 0x12, 0x3c, 0x41, 0xdd, 0x3c, 0xe2, 0x19,
	0x84, 0xb5, 0x2d, 0xdb, 0xe8, 0xef, 0x0c, 0x5a, 0x07, 0x9e, 0xb7, 0xc5, 0xbb, 0x77, 0xa6, 0x68,
	0xb5, 0x56, 0xd0, 0xc9, 0xd7, 0x53, 0xf7, 0xa7, 0x81, 0x3a, 0xb7, 0x00, 0xf8, 0x04, 0xed, 0x6a,
	0x88, 0x6d, 0xf4, 0x8d, 0x41, 0xeb, 0xe0, 0x70, 0xa3, 0x7e, 0xb5, 0xda, 0x6c, 0xe8, 0xbd, 0x61,
	0xb9, 0x14, 0x45, 0x0a, 0x4c, 0x12, 0x49, 0x39, 0xd3, 0x5a, 0x23, 0xeb, 0xea, 0x77, 0xaf, 0x11,
	0x94, 0x3a, 0xf8, 0x03, 0xea, 0x68, 0x3b, 0xf3, 0x10, 0x66, 0xc0, 0x64, 0x6e, 0x9b, 0xda, 0xf8,
	0x93, 0xad, 0xc6, 0xb5, 0xa5, 0xf9, 0x91, 0x22, 0x05, 0x6d, 0xb8, 0x49, 0x72, 0xfc, 0x00, 0xa1,
	0x3c, 0xfa, 0x0c, 0x29, 0x09, 0x0b, 0x91, 0xd8, 0x3b, 0x7d, 0x63, 0xb0, 0x17, 0xec, 0x95, 0x95,
	0x89, 0x48, 0xdc, 0x6f, 0x26, 0x6a, 0xad, 0x91, 0xf1, 0x43, 0xd4, 0x95, 0x34, 0x85, 0xb0, 0x60,
	0xf4, 0x32, 0x64, 0x84, 0x71, 0xbd, 0x9b, 0x15, 0xb4, 0x55, 0x75, 0xc2, 0xe8, 0xe5, 0x7b, 0xc2,
	0x38, 0xc6, 0xc8, 0x92, 0xf3, 0x0c, 0x6c, 0x53, 0xcb, 0xe9, 0x18, 0x3f, 0x47, 0x26, 0x8d, 0xed,
	0x1d, 0x6d, 0xf8, 0xd1, 0x96, 0x4b, 0xbc, 0x85, 0xf9, 0x39, 0x49, 0x8a, 0x7a, 0x7b, 0x93, 0xc6,
	0x78, 0x8c, 0x76, 0x73, 0x49, 0x24, 0xd8, 0x96, 0xbe, 0xe5, 0x5d, 0x57, 0x3e, 0x53, 0x9c, 0x63,
	0x75, 0x40, 0x15, 0xe0, 0xd7, 0xa8, 0x19, 0x43, 0x02, 0x12, 0xec, 0x5d, 0x2d, 0xf3, 0xf4, 0x8e,
	0x32, 0x63, 0x4d, 0x3a, 0x6e, 0x04, 0x15, 0x7d, 0xd4, 0x44, 0x56, 0x4c, 0x24, 0x71, 0xbf, 0x1a,
	0xf5, 0x7d, 0xf4, 0x24, 0xfc, 0x0e, 0x21, 0x22, 0xa5, 0xa0, 0x17, 0x85, 0x84, 0xdc, 0xb6, 0xfe,
	0x67, 0xdb, 0x35, 0x01, 0xfc, 0x0c, 0xd9, 0xb1, 0xe0, 0x59, 0x06, 0x71, 0x78, 0x53, 0x0d, 0x23,
	0x5e, 0x30, 0xa9, 0x37, 0xe8, 0x04, 0xf7, 0xab, 0xfe, 0x8b, 0x55, 0xfb, 0xa5, 0xea, 0xba, 0xdd,
	0xea, 0xd1, 0x57, 0xd6, 0x47, 0x3f, 0x8c, 0xab, 0x85, 0x63, 0x5c, 0x2f, 0x1c, 0xe3, 0xcf, 0xc2,
	0x31, 0xbe, 0x2c, 0x9d, 0xc6, 0xf5, 0xd2, 0x69, 0xfc, 0x5a, 0x3a, 0x0d, 0xe4, 0x52, 0xbe, 0xed,
	0x0c, 0xa3, 0x4e, 0xfd, 0xa8, 0x4f, 0x55, 0xeb, 0xd4, 0xf8, 0xf4, 0x6a, 0xfa, 0x2f, 0x89, 0xaa,
	0x0f, 0x36, 0x49, 0x20, 0x92, 0x5c, 0xf8, 0x99, 0xba, 0x8e, 0x4f, 0x99, 0x04, 0xc1, 0x48, 0xe2,
	0xeb, 0x4c, 0xab, 0x4e, 0x81, 0xad, 0xff, 0x3e, 0xbe, 0x9b, 0xbd, 0x93, 0x0c, 0xd8, 0xc7, 0x95,
	0x8a, 0xd6, 0xf7, 0xea, 0x69, 0xde, 0xf9, 0xf0, 0xa2, 0xa9, 0x79, 0x87, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xb2, 0xcc, 0xf5, 0x8c, 0x8a, 0x04, 0x00, 0x00,
}

func (m *EntitiesData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EntitiesData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EntitiesData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ScopeEntities) > 0 {
		for iNdEx := len(m.ScopeEntities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ScopeEntities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEntities(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ScopeEntities) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScopeEntities) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScopeEntities) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SchemaUrl) > 0 {
		i -= len(m.SchemaUrl)
		copy(dAtA[i:], m.SchemaUrl)
		i = encodeVarintEntities(dAtA, i, uint64(len(m.SchemaUrl)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EntityEvents) > 0 {
		for iNdEx := len(m.EntityEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EntityEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEntities(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Scope.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEntities(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EntityEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EntityEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EntityEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		{
			size := m.Data.Size()
			i -= size
			if _, err := m.Data.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Id) > 0 {
		for iNdEx := len(m.Id) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Id[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEntities(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintEntities(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x12
	}
	if m.TimeUnixNano != 0 {
		i = encodeVarintEntities(dAtA, i, uint64(m.TimeUnixNano))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EntityEvent_State) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EntityEvent_State) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.State != nil {
		{
			size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEntities(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *EntityEvent_Delete) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EntityEvent_Delete) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Delete != nil {
		{
			size, err := m.Delete.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEntities(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *EntityState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EntityState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EntityState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DroppedAttributesCount != 0 {
		i = encodeVarintEntities(dAtA, i, uint64(m.DroppedAttributesCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Attributes) > 0 {
		for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEntities(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	return len(dAtA) - i, nil
}

func (m *EntityDelete) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EntityDelete) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EntityDelete) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintEntities(dAtA []byte, offset int, v uint64) int {
	offset -= sovEntities(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EntitiesData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ScopeEntities) > 0 {
		for _, e := range m.ScopeEntities {
			l = e.Size()
			n += 1 + l + sovEntities(uint64(l))
		}
	}
	return n
}

func (m *ScopeEntities) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Scope.Size()
	n += 1 + l + sovEntities(uint64(l))
	if len(m.EntityEvents) > 0 {
		for _, e := range m.EntityEvents {
			l = e.Size()
			n += 1 + l + sovEntities(uint64(l))
		}
	}
	l = len(m.SchemaUrl)
	if l > 0 {
		n += 1 + l + sovEntities(uint64(l))
	}
	return n
}

func (m *EntityEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TimeUnixNano != 0 {
		n += 1 + sovEntities(uint64(m.TimeUnixNano))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovEntities(uint64(l))
	}
	if len(m.Id) > 0 {
		for _, e := range m.Id {
			l = e.Size()
			n += 1 + l + sovEntities(uint64(l))
		}
	}
	if m.Data != nil {
		n += m.Data.Size()
	}
	return n
}

func (m *EntityEvent_State) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.State != nil {
		l = m.State.Size()
		n += 1 + l + sovEntities(uint64(l))
	}
	return n
}
func (m *EntityEvent_Delete) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Delete != nil {
		l = m.Delete.Size()
		n += 1 + l + sovEntities(uint64(l))
	}
	return n
}
func (m *EntityState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Attributes) > 0 {
		for _, e := range m.Attributes {
			l = e.Size()
			n += 1 + l + sovEntities(uint64(l))
		}
	}
	if m.DroppedAttributesCount != 0 {
		n += 1 + sovEntities(uint64(m.DroppedAttributesCount))
	}
	return n
}

func (m *EntityDelete) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovEntities(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEntities(x uint64) (n int) {
	return sovEntities(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EntitiesData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntities
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EntitiesData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EntitiesData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScopeEntities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntities
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScopeEntities = append(m.ScopeEntities, &ScopeEntities{})
			if err := m.ScopeEntities[len(m.ScopeEntities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEntities(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEntities
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScopeEntities) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntities
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScopeEntities: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScopeEntities: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scope", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntities
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Scope.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntityEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntities
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntityEvents = append(m.EntityEvents, &EntityEvent{})
			if err := m.EntityEvents[len(m.EntityEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEntities
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEntities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SchemaUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEntities(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEntities
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EntityEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntities
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EntityEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EntityEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnixNano", wireType)
			}
			m.TimeUnixNano = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeUnixNano |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEntities
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEntities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntities
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id, v1.KeyValue{})
			if err := m.Id[len(m.Id)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntities
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &EntityState{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Data = &EntityEvent_State{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delete", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntities
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &EntityDelete{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Data = &EntityEvent_Delete{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEntities(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEntities
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EntityState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntities
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EntityState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EntityState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntities
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntities
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, v1.KeyValue{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DroppedAttributesCount", wireType)
			}
			m.DroppedAttributesCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DroppedAttributesCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEntities(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEntities
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EntityDelete) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntities
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EntityDelete: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EntityDelete: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipEntities(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEntities
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEntities(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEntities
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntities
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEntities
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEntities
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEntities
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEntities        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEntities          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEntities = fmt.Errorf("proto: unexpected end of group")
)
